//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public Nullable<int> id_type_material { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<int> warehouse_amount { get; set; }
        public Nullable<int> min_amount { get; set; }
        public Nullable<int> amount_in_package { get; set; }
        public string unit_of_measurement { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        public override string ToString()
        {
            return title;
        }
    }
}
