//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public Nullable<int> id_type_partner { get; set; }
        public string INN { get; set; }
        public Nullable<int> rating { get; set; }
        public string director { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    
        public virtual PartnerType PartnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; } 
        public override string ToString()
        {
            return title;
        }
    }
}
