//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_products
    {
        public int ID { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_request { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Request Request { get; set; }
        
    }
    
}
