//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdk0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Request_products = new HashSet<Request_products>();
        }
    
        public int ID { get; set; }
        public Nullable<int> id_partner { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_products> Request_products { get; set; }
        public string Partner_type => Partner.PartnerType.title;
        public string address => Partner.address;
        public string phone => Partner.phone;
        public double? rating => Partner.rating;
    }
}
